"""seven

Revision ID: 1bd7480b8fd9
Revises: 2bc856cb783d
Create Date: 2022-04-28 22:41:28.408174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd7480b8fd9'
down_revision = '2bc856cb783d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provincescenic', sa.Column('ticketsNum', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provincescenic', 'ticketsNum')
    # ### end Alembic commands ###
