"""five

Revision ID: 2bc856cb783d
Revises: 505d1cefc15d
Create Date: 2022-04-28 14:43:37.607966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc856cb783d'
down_revision = '505d1cefc15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenic5a',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provinceName', sa.String(length=200), nullable=False),
    sa.Column('Scenic5AName', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenic5a')
    # ### end Alembic commands ###
