"""three

Revision ID: 445a0b6d2c2e
Revises: 5f056f77d724
Create Date: 2022-04-26 01:26:17.655640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '445a0b6d2c2e'
down_revision = '5f056f77d724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'tt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('tt', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
