"""first

Revision ID: c68dbcf302ae
Revises: 
Create Date: 2022-04-25 01:27:25.994880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c68dbcf302ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('must_visit_place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('must_visit_place',
    sa.Column('id', mysql.INTEGER(display_width=20), autoincrement=True, nullable=False, comment='id'),
    sa.Column('city_name', mysql.VARCHAR(length=20), nullable=False, comment='城市名'),
    sa.Column('place_name', mysql.VARCHAR(length=30), nullable=False, comment='景点名'),
    sa.Column('place_introduce', mysql.VARCHAR(length=200), nullable=False, comment='景点简介'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('test')
    # ### end Alembic commands ###
