"""eight

Revision ID: fbbf92d806d4
Revises: 1bd7480b8fd9
Create Date: 2022-04-29 06:15:08.408858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbf92d806d4'
down_revision = '1bd7480b8fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenictype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provinceName', sa.String(length=200), nullable=False),
    sa.Column('ScenicType', sa.String(length=200), nullable=False),
    sa.Column('ScenicNum', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenictype')
    # ### end Alembic commands ###
